drop table if exists race CASCADE;
drop table if exists rider CASCADE;
create table race (id bigint generated by default as identity, name varchar(255) not null, type varchar(30), primary key (id));
create table rider (id bigint generated by default as identity, name varchar(255) not null, date_of_birth timestamp, sex varchar(1), primary key (id));
